//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace JadeQuoteSystem.Module.BusinessObjects.Database
{

    public partial class customerinfo : XPLiteObject
    {
        int fcustinfid;
        [Key]
        public int custinfid
        {
            get { return fcustinfid; }
            set { SetPropertyValue<int>(nameof(custinfid), ref fcustinfid, value); }
        }
        string faction;
        [Size(3)]
        public string action
        {
            get { return faction; }
            set { SetPropertyValue<string>(nameof(action), ref faction, value); }
        }
        string fdocoutp;
        [Size(5)]
        public string docoutp
        {
            get { return fdocoutp; }
            set { SetPropertyValue<string>(nameof(docoutp), ref fdocoutp, value); }
        }
        string fcustno;
        [Size(6)]
        public string custno
        {
            get { return fcustno; }
            set { SetPropertyValue<string>(nameof(custno), ref fcustno, value); }
        }
        string fdescrip;
        [Size(40)]
        public string descrip
        {
            get { return fdescrip; }
            set { SetPropertyValue<string>(nameof(descrip), ref fdescrip, value); }
        }
    }

}
