//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace JadeQuoteSystem.Module.BusinessObjects.Database
{

    public partial class holddetailvalues : XPLiteObject
    {
        int fholddtlid;
        [Key]
        public int holddtlid
        {
            get { return fholddtlid; }
            set { SetPropertyValue<int>(nameof(holddtlid), ref fholddtlid, value); }
        }
        string fordseq;
        [Size(4)]
        public string ordseq
        {
            get { return fordseq; }
            set { SetPropertyValue<string>(nameof(ordseq), ref fordseq, value); }
        }
        string fdescrip;
        [Size(30)]
        public string descrip
        {
            get { return fdescrip; }
            set { SetPropertyValue<string>(nameof(descrip), ref fdescrip, value); }
        }
        string fitemum;
        [Size(4)]
        public string itemum
        {
            get { return fitemum; }
            set { SetPropertyValue<string>(nameof(itemum), ref fitemum, value); }
        }
        decimal fumbytime;
        public decimal umbytime
        {
            get { return fumbytime; }
            set { SetPropertyValue<decimal>(nameof(umbytime), ref fumbytime, value); }
        }
        decimal fpercval;
        public decimal percval
        {
            get { return fpercval; }
            set { SetPropertyValue<decimal>(nameof(percval), ref fpercval, value); }
        }
        decimal fm_rate;
        public decimal m_rate
        {
            get { return fm_rate; }
            set { SetPropertyValue<decimal>(nameof(m_rate), ref fm_rate, value); }
        }
    }

}
