//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace JadeQuoteSystem.Module.BusinessObjects.Database
{

    public partial class lookups : XPLiteObject
    {
        int flookupid;
        [Key]
        public int lookupid
        {
            get { return flookupid; }
            set { SetPropertyValue<int>(nameof(lookupid), ref flookupid, value); }
        }
        string fcode;
        [Size(5)]
        public string code
        {
            get { return fcode; }
            set { SetPropertyValue<string>(nameof(code), ref fcode, value); }
        }
        string fmeaning;
        [Size(50)]
        public string meaning
        {
            get { return fmeaning; }
            set { SetPropertyValue<string>(nameof(meaning), ref fmeaning, value); }
        }
        string ftype;
        [Size(20)]
        public string type
        {
            get { return ftype; }
            set { SetPropertyValue<string>(nameof(type), ref ftype, value); }
        }
        decimal fcode_len;
        public decimal code_len
        {
            get { return fcode_len; }
            set { SetPropertyValue<decimal>(nameof(code_len), ref fcode_len, value); }
        }
    }

}
