//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace JadeQuoteSystem.Module.BusinessObjects.Database
{

    public partial class quotebase : XPLiteObject
    {
        int fquotebsid;
        [Key]
        public int quotebsid
        {
            get { return fquotebsid; }
            set { SetPropertyValue<int>(nameof(quotebsid), ref fquotebsid, value); }
        }
        quoteheader fquotehdrid;
        [Indexed(Name = @"quotehdrid")]
        public quoteheader quotehdrid
        {
            get { return fquotehdrid; }
            set { SetPropertyValue<quoteheader>(nameof(quotehdrid), ref fquotehdrid, value); }
        }
        int fdefchargeid;
        public int defchargeid
        {
            get { return fdefchargeid; }
            set { SetPropertyValue<int>(nameof(defchargeid), ref fdefchargeid, value); }
        }
        string fdescrip;
        [Size(40)]
        public string descrip
        {
            get { return fdescrip; }
            set { SetPropertyValue<string>(nameof(descrip), ref fdescrip, value); }
        }
        decimal famount;
        public decimal amount
        {
            get { return famount; }
            set { SetPropertyValue<decimal>(nameof(amount), ref famount, value); }
        }
        string frt_code;
        [Size(10)]
        public string rt_code
        {
            get { return frt_code; }
            set { SetPropertyValue<string>(nameof(rt_code), ref frt_code, value); }
        }
    }

}
