//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace JadeQuoteSystem.Module.BusinessObjects.Database
{

    public partial class quoteitem : XPLiteObject
    {
        int fquoteitemid;
        [Key]
        public int quoteitemid
        {
            get { return fquoteitemid; }
            set { SetPropertyValue<int>(nameof(quoteitemid), ref fquoteitemid, value); }
        }
        string fitem;
        [Size(20)]
        public string item
        {
            get { return fitem; }
            set { SetPropertyValue<string>(nameof(item), ref fitem, value); }
        }
        string fdescrip;
        [Size(60)]
        public string descrip
        {
            get { return fdescrip; }
            set { SetPropertyValue<string>(nameof(descrip), ref fdescrip, value); }
        }
        string fstockum;
        [Size(6)]
        public string stockum
        {
            get { return fstockum; }
            set { SetPropertyValue<string>(nameof(stockum), ref fstockum, value); }
        }
        string fprodclas;
        [Size(6)]
        public string prodclas
        {
            get { return fprodclas; }
            set { SetPropertyValue<string>(nameof(prodclas), ref fprodclas, value); }
        }
    }

}
