//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace JadeQuoteSystem.Module.BusinessObjects.Database
{

    public partial class quotesystem : XPLiteObject
    {
        int foid;
        [Key]
        public int oid
        {
            get { return foid; }
            set { SetPropertyValue<int>(nameof(oid), ref foid, value); }
        }
        string fcompany;
        [Size(35)]
        public string company
        {
            get { return fcompany; }
            set { SetPropertyValue<string>(nameof(company), ref fcompany, value); }
        }
        string faddress;
        [Size(30)]
        public string address
        {
            get { return faddress; }
            set { SetPropertyValue<string>(nameof(address), ref faddress, value); }
        }
        string faddress2;
        [Size(30)]
        public string address2
        {
            get { return faddress2; }
            set { SetPropertyValue<string>(nameof(address2), ref faddress2, value); }
        }
        string fcity;
        [Size(20)]
        public string city
        {
            get { return fcity; }
            set { SetPropertyValue<string>(nameof(city), ref fcity, value); }
        }
        string fstate;
        [Size(2)]
        public string state
        {
            get { return fstate; }
            set { SetPropertyValue<string>(nameof(state), ref fstate, value); }
        }
        string fzip;
        [Size(9)]
        public string zip
        {
            get { return fzip; }
            set { SetPropertyValue<string>(nameof(zip), ref fzip, value); }
        }
        string fphone;
        [Size(10)]
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>(nameof(phone), ref fphone, value); }
        }
        string ffax;
        [Size(10)]
        public string fax
        {
            get { return ffax; }
            set { SetPropertyValue<string>(nameof(fax), ref ffax, value); }
        }
        string femail;
        [Size(30)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        decimal frollover;
        public decimal rollover
        {
            get { return frollover; }
            set { SetPropertyValue<decimal>(nameof(rollover), ref frollover, value); }
        }
        string facct_path;
        [Size(70)]
        public string acct_path
        {
            get { return facct_path; }
            set { SetPropertyValue<string>(nameof(acct_path), ref facct_path, value); }
        }
        string fmanuf_path;
        [Size(70)]
        public string manuf_path
        {
            get { return fmanuf_path; }
            set { SetPropertyValue<string>(nameof(manuf_path), ref fmanuf_path, value); }
        }
        string friata_path;
        [Size(70)]
        public string riata_path
        {
            get { return friata_path; }
            set { SetPropertyValue<string>(nameof(riata_path), ref friata_path, value); }
        }
    }

}
