//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp;
using DevExpress.Persistent.Base;
namespace JadeQuoteSystem.Module.BusinessObjects.Database
{
             
    [XafDisplayName("Quote Maintenance")]
    [DefaultClassOptions]
    [DefaultListViewOptions()]
    public partial class quoteheader : XPLiteObject
    {
        int fquotehdrid;
        [Key]
        public int quotehdrid
        {
            get { return fquotehdrid; }
            set { SetPropertyValue<int>(nameof(quotehdrid), ref fquotehdrid, value); }
        }
        string fquoteno;
        [Indexed(Name = @"quoteno")]
        [Size(10)]
        public string quoteno
        {
            get { return fquoteno; }
            set { SetPropertyValue<string>(nameof(quoteno), ref fquoteno, value); }
        }
        DateTime fquotedate;
        public DateTime quotedate
        {
            get { return fquotedate; }
            set { SetPropertyValue<DateTime>(nameof(quotedate), ref fquotedate, value); }
        }
        string frevision;
        [Size(5)]
        public string revision
        {
            get { return frevision; }
            set { SetPropertyValue<string>(nameof(revision), ref frevision, value); }
        }
        string fitemno;
        [Size(15)]
        public string itemno
        {
            get { return fitemno; }
            set { SetPropertyValue<string>(nameof(itemno), ref fitemno, value); }
        }
        string fitem_uom;
        [Size(10)]
        public string item_uom
        {
            get { return fitem_uom; }
            set { SetPropertyValue<string>(nameof(item_uom), ref fitem_uom, value); }
        }
        decimal fminpurqty;
        public decimal minpurqty
        {
            get { return fminpurqty; }
            set { SetPropertyValue<decimal>(nameof(minpurqty), ref fminpurqty, value); }
        }
        string fitem_matl;
        [Size(10)]
        public string item_matl
        {
            get { return fitem_matl; }
            set { SetPropertyValue<string>(nameof(item_matl), ref fitem_matl, value); }
        }
        string fcustno;
        [Size(6)]
        public string custno
        {
            get { return fcustno; }
            set { SetPropertyValue<string>(nameof(custno), ref fcustno, value); }
        }
        string fcontact;
        [Size(25)]
        public string contact
        {
            get { return fcontact; }
            set { SetPropertyValue<string>(nameof(contact), ref fcontact, value); }
        }
        string fsalesmn;
        [Size(10)]
        public string salesmn
        {
            get { return fsalesmn; }
            set { SetPropertyValue<string>(nameof(salesmn), ref fsalesmn, value); }
        }
        string fquoteby;
        [Size(10)]
        public string quoteby
        {
            get { return fquoteby; }
            set { SetPropertyValue<string>(nameof(quoteby), ref fquoteby, value); }
        }
        string fqtnotes;
        [Size(SizeAttribute.Unlimited)]
        public string qtnotes
        {
            get { return fqtnotes; }
            set { SetPropertyValue<string>(nameof(qtnotes), ref fqtnotes, value); }
        }
        string fdelivery;
        [Size(35)]
        public string delivery
        {
            get { return fdelivery; }
            set { SetPropertyValue<string>(nameof(delivery), ref fdelivery, value); }
        }
        string frm_item;
        [Size(15)]
        public string rm_item
        {
            get { return frm_item; }
            set { SetPropertyValue<string>(nameof(rm_item), ref frm_item, value); }
        }
        string frm_uom;
        [Size(5)]
        public string rm_uom
        {
            get { return frm_uom; }
            set { SetPropertyValue<string>(nameof(rm_uom), ref frm_uom, value); }
        }
        decimal fsingpartunit;
        public decimal singpartunit
        {
            get { return fsingpartunit; }
            set { SetPropertyValue<decimal>(nameof(singpartunit), ref fsingpartunit, value); }
        }
        decimal fmaterialpric;
        public decimal materialpric
        {
            get { return fmaterialpric; }
            set { SetPropertyValue<decimal>(nameof(materialpric), ref fmaterialpric, value); }
        }
        decimal fmoldingrate;
        public decimal moldingrate
        {
            get { return fmoldingrate; }
            set { SetPropertyValue<decimal>(nameof(moldingrate), ref fmoldingrate, value); }
        }
        decimal fmachinerate;
        public decimal machinerate
        {
            get { return fmachinerate; }
            set { SetPropertyValue<decimal>(nameof(machinerate), ref fmachinerate, value); }
        }
        decimal ftotnumpieces;
        public decimal totnumpieces
        {
            get { return ftotnumpieces; }
            set { SetPropertyValue<decimal>(nameof(totnumpieces), ref ftotnumpieces, value); }
        }
        decimal ftotmatqty;
        public decimal totmatqty
        {
            get { return ftotmatqty; }
            set { SetPropertyValue<decimal>(nameof(totmatqty), ref ftotmatqty, value); }
        }
        string fqtstatus;
        [Size(3)]
        public string qtstatus
        {
            get { return fqtstatus; }
            set { SetPropertyValue<string>(nameof(qtstatus), ref fqtstatus, value); }
        }
        string femail;
        [Size(40)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string falt_custno;
        [Size(10)]
        public string alt_custno
        {
            get { return falt_custno; }
            set { SetPropertyValue<string>(nameof(alt_custno), ref falt_custno, value); }
        }
        string fupdmark;
        [Size(50)]
        public string updmark
        {
            get { return fupdmark; }
            set { SetPropertyValue<string>(nameof(updmark), ref fupdmark, value); }
        }
        [Association(@"quoteqtysReferencesquoteheader")]
        public XPCollection<quoteqtys> quoteqtysCollection { get { return GetCollection<quoteqtys>(nameof(quoteqtysCollection)); } }
        [Association(@"quotedetailReferencesquoteheader")]
        public XPCollection<quotedetail> quotedetails { get { return GetCollection<quotedetail>(nameof(quotedetails)); } }
    }

}
