//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace JadeQuoteSystem.Module.BusinessObjects.Database
{

    public partial class quotedefaults : XPLiteObject
    {
        int fquotesysid;
        [Key]
        public int quotesysid
        {
            get { return fquotesysid; }
            set { SetPropertyValue<int>(nameof(quotesysid), ref fquotesysid, value); }
        }
        decimal fmoldrate;
        public decimal moldrate
        {
            get { return fmoldrate; }
            set { SetPropertyValue<decimal>(nameof(moldrate), ref fmoldrate, value); }
        }
        decimal fmachinerate;
        public decimal machinerate
        {
            get { return fmachinerate; }
            set { SetPropertyValue<decimal>(nameof(machinerate), ref fmachinerate, value); }
        }
        decimal fohrate;
        public decimal ohrate
        {
            get { return fohrate; }
            set { SetPropertyValue<decimal>(nameof(ohrate), ref fohrate, value); }
        }
        decimal fmarkup;
        public decimal markup
        {
            get { return fmarkup; }
            set { SetPropertyValue<decimal>(nameof(markup), ref fmarkup, value); }
        }
        decimal fslcomm;
        public decimal slcomm
        {
            get { return fslcomm; }
            set { SetPropertyValue<decimal>(nameof(slcomm), ref fslcomm, value); }
        }
    }

}
