//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace JadeQuoteSystem.Module.BusinessObjects.Database
{

    public partial class quotedetail : XPLiteObject
    {
        int fquotedtlid;
        [Key]
        public int quotedtlid
        {
            get { return fquotedtlid; }
            set { SetPropertyValue<int>(nameof(quotedtlid), ref fquotedtlid, value); }
        }
        quoteheader fquotehdrid;
        [Indexed(Name = @"quotehdrid")]
        [Association(@"quotedetailReferencesquoteheader")]
        public quoteheader quotehdrid
        {
            get { return fquotehdrid; }
            set { SetPropertyValue<quoteheader>(nameof(quotehdrid), ref fquotehdrid, value); }
        }
        int fquoteqtysid;
        [Indexed(Name = @"quoteqtysi")]
        public int quoteqtysid
        {
            get { return fquoteqtysid; }
            set { SetPropertyValue<int>(nameof(quoteqtysid), ref fquoteqtysid, value); }
        }
        int fquotebsid;
        public int quotebsid
        {
            get { return fquotebsid; }
            set { SetPropertyValue<int>(nameof(quotebsid), ref fquotebsid, value); }
        }
        string fordseq;
        [Size(4)]
        public string ordseq
        {
            get { return fordseq; }
            set { SetPropertyValue<string>(nameof(ordseq), ref fordseq, value); }
        }
        string fdescrip;
        [Size(40)]
        public string descrip
        {
            get { return fdescrip; }
            set { SetPropertyValue<string>(nameof(descrip), ref fdescrip, value); }
        }
        string fitemum;
        [Size(10)]
        public string itemum
        {
            get { return fitemum; }
            set { SetPropertyValue<string>(nameof(itemum), ref fitemum, value); }
        }
        decimal fumbytime;
        public decimal umbytime
        {
            get { return fumbytime; }
            set { SetPropertyValue<decimal>(nameof(umbytime), ref fumbytime, value); }
        }
        decimal fpriceamt;
        public decimal priceamt
        {
            get { return fpriceamt; }
            set { SetPropertyValue<decimal>(nameof(priceamt), ref fpriceamt, value); }
        }
        decimal fextprice;
        public decimal extprice
        {
            get { return fextprice; }
            set { SetPropertyValue<decimal>(nameof(extprice), ref fextprice, value); }
        }
        decimal fslmargin;
        public decimal slmargin
        {
            get { return fslmargin; }
            set { SetPropertyValue<decimal>(nameof(slmargin), ref fslmargin, value); }
        }
        decimal fpercval;
        public decimal percval
        {
            get { return fpercval; }
            set { SetPropertyValue<decimal>(nameof(percval), ref fpercval, value); }
        }
    }

}
