//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace JadeQuoteSystem.Module.BusinessObjects.Database
{

    public partial class quotecustomer : XPLiteObject
    {
        int fquotecustid;
        [Key]
        public int quotecustid
        {
            get { return fquotecustid; }
            set { SetPropertyValue<int>(nameof(quotecustid), ref fquotecustid, value); }
        }
        string fcoid;
        [Size(6)]
        public string coid
        {
            get { return fcoid; }
            set { SetPropertyValue<string>(nameof(coid), ref fcoid, value); }
        }
        string fconame;
        [Size(35)]
        public string coname
        {
            get { return fconame; }
            set { SetPropertyValue<string>(nameof(coname), ref fconame, value); }
        }
        string fstreet1;
        [Size(35)]
        public string street1
        {
            get { return fstreet1; }
            set { SetPropertyValue<string>(nameof(street1), ref fstreet1, value); }
        }
        string fstreet2;
        [Size(35)]
        public string street2
        {
            get { return fstreet2; }
            set { SetPropertyValue<string>(nameof(street2), ref fstreet2, value); }
        }
        string fcity;
        [Size(20)]
        public string city
        {
            get { return fcity; }
            set { SetPropertyValue<string>(nameof(city), ref fcity, value); }
        }
        string fstate;
        [Size(10)]
        public string state
        {
            get { return fstate; }
            set { SetPropertyValue<string>(nameof(state), ref fstate, value); }
        }
        string fzipcode;
        [Size(10)]
        public string zipcode
        {
            get { return fzipcode; }
            set { SetPropertyValue<string>(nameof(zipcode), ref fzipcode, value); }
        }
        string fcontact;
        [Size(40)]
        public string contact
        {
            get { return fcontact; }
            set { SetPropertyValue<string>(nameof(contact), ref fcontact, value); }
        }
        string fphone;
        [Size(20)]
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>(nameof(phone), ref fphone, value); }
        }
        string femail;
        [Size(40)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
    }

}
