//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace JadeQuoteSystem.Module.BusinessObjects.Database
{

    public partial class quoteqtys : XPLiteObject
    {
        quoteheader fquotehdrid;
        [Indexed(Name = @"quotehdrid")]
        [Association(@"quoteqtysReferencesquoteheader")]
        public quoteheader quotehdrid
        {
            get { return fquotehdrid; }
            set { SetPropertyValue<quoteheader>(nameof(quotehdrid), ref fquotehdrid, value); }
        }
        int fquoteqtysid;
        [Key]
        public int quoteqtysid
        {
            get { return fquoteqtysid; }
            set { SetPropertyValue<int>(nameof(quoteqtysid), ref fquoteqtysid, value); }
        }
        decimal fquote_qty;
        public decimal quote_qty
        {
            get { return fquote_qty; }
            set { SetPropertyValue<decimal>(nameof(quote_qty), ref fquote_qty, value); }
        }
        decimal fqt_porder;
        public decimal qt_porder
        {
            get { return fqt_porder; }
            set { SetPropertyValue<decimal>(nameof(qt_porder), ref fqt_porder, value); }
        }
        decimal fqt_ppart;
        public decimal qt_ppart
        {
            get { return fqt_ppart; }
            set { SetPropertyValue<decimal>(nameof(qt_ppart), ref fqt_ppart, value); }
        }
        decimal fmarkup;
        public decimal markup
        {
            get { return fmarkup; }
            set { SetPropertyValue<decimal>(nameof(markup), ref fmarkup, value); }
        }
        decimal fsalescomm;
        public decimal salescomm
        {
            get { return fsalescomm; }
            set { SetPropertyValue<decimal>(nameof(salescomm), ref fsalescomm, value); }
        }
        char fdisp_ppu;
        public char disp_ppu
        {
            get { return fdisp_ppu; }
            set { SetPropertyValue<char>(nameof(disp_ppu), ref fdisp_ppu, value); }
        }
    }

}
